services:

    fiedsch_ligaverwaltung.rankinghelper:
        class: Fiedsch\LigaverwaltungBundle\Helper\RankingHelper
        public: true

    fiedsch_ligaverwaltung.migration.haspaidmigration:
        class: Fiedsch\LigaverwaltungBundle\Migration\HasPaidMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    fiedsch_ligaverwaltung.migration.patchsaisonmigration:
        class: Fiedsch\LigaverwaltungBundle\Migration\PatchSaisonMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }
    fiedsch_ligaverwaltung.controller.backend_controller:
        class: Fiedsch\LigaverwaltungBundle\Controller\LigaverwaltungBackendController
        tags: ['controller.service_arguments']
        calls:
            - [ setContainer, [ '@service_container' ] ]

    # Siehe auch https://contao.slack.com/archives/CK4J0KNDB/p1704882456107879
    # Slack Account cms@andreas-fieger.de
