services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    fiedsch.ligaverwaltung.command.rechnungsdaten:
        class: Fiedsch\Ligaverwaltung\Command\RechnungsDatenAbzugCommand
        arguments:
            - '@twig'

    fiedsch.ligaverwaltung.command.spielerliste:
        class: Fiedsch\Ligaverwaltung\Command\SpielerAbzugCommand

    fiedsch.ligaverwaltung.command.begegnungenerstellen:
        class: Fiedsch\Ligaverwaltung\Command\BegegnungenErstellenCommand

    fiedsch.ligaverwaltung.command.fixdata:
            class: Fiedsch\Ligaverwaltung\Command\FixDataCommand

