services:
    _defaults:
        autoconfigure: true
    # _instanceof:
    #     Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
    #         calls:
    #             - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

    Fiedsch\LigaverwaltungBundle\Controller\ContentElement\RankingController:
        arguments:
            - '@fiedsch_ligaverwaltung.rankinghelper'

