services:
    _defaults:
        autoconfigure: true
        autowire: true

    fiedsch_ligaverwaltung.helper.ranking:
        class: Fiedsch\Ligaverwaltung\Helper\RankingHelper
        public: true

    fiedsch_ligaverwaltung.migration.haspaidmigration:
        class: Fiedsch\Ligaverwaltung\Migration\HasPaidMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    fiedsch_ligaverwaltung.migration.patchsaisonmigration:
        class: Fiedsch\Ligaverwaltung\Migration\PatchSaisonMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    fiedsch_ligaverwaltung.listener.buttons_callback:
        class: Fiedsch\Ligaverwaltung\EventListener\DataContainer\EditButtonsCallbackListener

    # For the rest: Do not use an alias (see https://docs.contao.org/5.x/dev/guides/coding-standards/)
    # fiedsch_ligaverwaltung.controller.ical:
    #    class: Fiedsch\Ligaverwaltung\Controller\Frontend\IcalController
    Fiedsch\Ligaverwaltung\Controller\Frontend\IcalController:
        arguments:
            - '@contao.framework'

    Fiedsch\Ligaverwaltung\Controller\Frontend\JsonController:
        public: true
        arguments:
            - '@contao.framework'

    Fiedsch\Ligaverwaltung\Controller\Backend\PlayerHistoryController:
        public: true
        arguments:
            - '@twig'

    Fiedsch\Ligaverwaltung\Controller\ContentElement\RankingController:
        arguments:
            - '@fiedsch_ligaverwaltung.helper.ranking'

    Fiedsch\Ligaverwaltung\Controller\ContentElement\HighlightRankingController:
        arguments:
            - '@database_connection'

    Fiedsch\Ligaverwaltung\Controller\ContentElement\LigenlisteController: ~
    Fiedsch\Ligaverwaltung\Controller\ContentElement\MannschaftslisteController: ~
    Fiedsch\Ligaverwaltung\Controller\ContentElement\SpielberichtController: ~
    Fiedsch\Ligaverwaltung\Controller\ContentElement\SpielerlisteController: ~
    Fiedsch\Ligaverwaltung\Controller\ContentElement\MannschaftenuebersichtController: ~
    Fiedsch\Ligaverwaltung\Controller\ContentElement\SpielortinfoController: ~
    Fiedsch\Ligaverwaltung\Controller\ContentElement\SpielplanController: ~


    Fiedsch\Ligaverwaltung\Callback\BegegnungDataEntryForm:
        public: true
        arguments:
            - '@twig'
