services:
    _defaults:
        autoconfigure: true
        autowire: false

    fiedsch_ligaverwaltung.rankinghelper:
        class: Fiedsch\LigaverwaltungBundle\Helper\RankingHelper
        public: true

    fiedsch_ligaverwaltung.migration.haspaidmigration:
        class: Fiedsch\LigaverwaltungBundle\Migration\HasPaidMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    fiedsch_ligaverwaltung.migration.patchsaisonmigration:
        class: Fiedsch\LigaverwaltungBundle\Migration\PatchSaisonMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }
    fiedsch_ligaverwaltung.controller.backend_controller:
        class: Fiedsch\LigaverwaltungBundle\Controller\LigaverwaltungBackendController
        tags: ['controller.service_arguments']
        calls:
            - [ setContainer, [ '@service_container' ] ]

    #fiedsch_ligaverwaltung.controller.ical_controller:
    #    class: Fiedsch\LigaverwaltungBundle\Controller\IcalController
    Fiedsch\LigaverwaltungBundle\Controller\IcalController:
        arguments:
            - '@contao.framework'
        tags: ['controller.service_arguments']

    #fiedsch_ligaverwaltung.controller.json_controller:
    #    class: Fiedsch\LigaverwaltungBundle\Controller\JsonController
    Fiedsch\LigaverwaltungBundle\Controller\JsonController:
        arguments:
            - '@contao.framework'
        tags: ['controller.service_arguments']
